version: '3.7'

networks:
  common:

services:
  php:
    restart: always
    image: php:8.2-fpm
    command: php /var/www/artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - common

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - common

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - common
